export const AppError = {
    USER_NOT_EXIST: "User does not exist!",
    NO_USER_EXISTS: "No user exists!",
    USER_ALREADY_EXISTS: "User already exists!",
    INVALID_PAGE_SIZE: "invalid page size!",
    EMAIL_IS_TAKEN: "An account is already registered to this email address!",
    USER_TAG_IS_TAKEN: "This user tag is already taken!",
    DIALOG_NOT_EXIST: "Dialog does not exist!",
    ALL_USERS_ALREADY_IN_DIALOG: "All users already in dialog!",
    ADD_MEMBERS_TO_PRIVATE_DIALOG: "You can't add members to private dialog!",
    PRIVATE_DIALOG_MEMBER_COUNT: "Private dialog only can have 2 members!",
    TRYING_ADD_TO_DIALOG_YOURSELF: "You're trying to add yourself to the dialog!",
    NAME_OF_GROUP_DIALOG: "Group dialog could have a name!",
    CANT_GET_MEMBERS_OF_DIALOG: "Can't get members of dialog!",
    YOU_ARE_NOT_IN_DIALOG: "You're not a member of dialog!",
    MEMBER_NOT_EXIST: "Member does not exist!",
    MEMBER_ALREADY_EXISTS: "User is already a member of this dialog!",
    INCORRECT_PAGE: "Page does not exist!",
    AUTHORIZATION_ERROR: "Authorization error!",
    INCORRECT_PASSWORD: "Incorrect password!",
    SUFFICIENT_RIGHTS: "You do not have sufficient rights!",
    MESSAGE_NOT_EXISTS: "Message does not exists!",
    NOT_YOUR_MESSAGE: "Not your message!",
    SUBSCRIBE_ALREADY_EXISTS: "Subscribe already exists!",
    SUBSCRIBE_IS_NOT_CREATED: "Subscribe is not created!",
    CANT_GET_SUBSCRIBES: "Can't get subscribes!",
    CANT_GET_SUB_STATUS: "Can't get subscribe status!",
    SUB_NOT_EXISTS: "Subscribe does not exists!",
    THOUGHT_NOT_EXISTS: "Thought does not exists!",
    NOT_ENOUGH_RIGHTS: "You do not have the rights to do this!",
}